#!/bin/bash

python main.py --purpose train    --env 1011-transfer-learning-image-augmentation                  --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints > train-1011-retina50.log 2>&1
python main.py --purpose evaluate --env 1011-transfer-learning-image-augmentation                  --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011-transfer-learning-image-augmentation-body-shots-eval  --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-body-shots-eval --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011-transfer-learning-image-augmentation-cases-eval       --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-cases-eval      --eval_images --eval_heatmaps

python main.py --purpose train    --env 1011b-transfer-learning-image-augmentation                 --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints > train-1011b-retina50.log 2>&1
python main.py --purpose evaluate --env 1011b-transfer-learning-image-augmentation                 --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011b-transfer-learning-image-augmentation-body-shots-eval --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-body-shots-eval --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011b-transfer-learning-image-augmentation-cases-eval      --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-cases-eval      --eval_images --eval_heatmaps

python main.py --purpose train    --env 1011c-transfer-learning-image-augmentation                 --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints > train-1011c-retina50.log 2>&1
python main.py --purpose evaluate --env 1011c-transfer-learning-image-augmentation                 --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011c-transfer-learning-image-augmentation-body-shots-eval --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-body-shots-eval --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1011c-transfer-learning-image-augmentation-cases-eval      --gpu_no 2 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation --eval_name_suffix=-cases-eval      --eval_images --eval_heatmaps