#!/bin/bash

python main.py --purpose train    --env 1310-joint-cases-extracted-closeup-wounds     --loss_patience=6 --val_loss_patience=6                --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/home/blsa/projects/confidential/wound-detection/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation > train-1310-retina152.log 2>&1
python main.py --purpose evaluate --env 1310-joint-cases-extracted-closeup-wounds                                                            --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/home/blsa/projects/confidential/wound-detection/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1310-joint-cases-extracted-closeup-wounds-body-shots-eval                                            --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/home/blsa/projects/confidential/wound-detection/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation --eval_name_suffix=-body-shots-eval --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1310-joint-cases-extracted-closeup-wounds-cases-eval                                                 --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/home/blsa/projects/confidential/wound-detection/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation --eval_name_suffix=-cases-eval      --eval_images --eval_heatmaps

mkdir -p /checkpoints/1311a_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
cp /checkpoints/1310a_Joint_Cases_Extracted_Closeup_Wounds--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311a_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
mv /checkpoints/1311a_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311a_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/1311a_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152_0001.h5

mkdir -p /checkpoints/1311b_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
cp /checkpoints/1310b_Joint_Cases_Extracted_Closeup_Wounds--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311b_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
mv /checkpoints/1311b_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311b_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/1311b_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152_0001.h5

mkdir -p /checkpoints/1311c_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
cp /checkpoints/1310c_Joint_Cases_Extracted_Closeup_Wounds--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311c_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
mv /checkpoints/1311c_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311c_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/1311c_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152_0001.h5

mkdir -p /checkpoints/1311d_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
cp /checkpoints/1310d_Joint_Cases_Extracted_Closeup_Wounds--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311d_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152
mv /checkpoints/1311d_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/*latest.h5 /checkpoints/1311d_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152/1311d_Joint_Cases_Extracted_Closeup_Wounds_Fine_Tuning--RetinaNet-Resnet152_0001.h5

python main.py --purpose train    --env 1311-joint-cases-extracted-closeup-wounds-fine-tuning     --loss_patience=6 --val_loss_patience=6    --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation > train-1311-retina152.log 2>&1
python main.py --purpose evaluate --env 1311-joint-cases-extracted-closeup-wounds-fine-tuning                                                --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1311-joint-cases-extracted-closeup-wounds-fine-tuning-body-shots-eval                                --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1311-joint-cases-extracted-closeup-wounds-fine-tuning-cases-eval                                     --gpu_no=1 --net_type retina-resnet152 --data_dir=/home/blsa/projects/confidential/wound-detection/data --checkpoint_dir=/checkpoints --eval_dir=/home/blsa/projects/confidential/wound-detection/evaluation                                     --eval_images --eval_heatmaps