#!/bin/bash

python main.py --purpose train    --env 1032-joint-puppet-close-up-wounds-strong-imgaug                                       --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints/ --eval_dir=/checkpoints/evaluation > train-1032-retina50.log 2>&1
python main.py --purpose evaluate --env 1032-joint-puppet-close-up-wounds-strong-imgaug                                       --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints/ --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1032-joint-puppet-close-up-wounds-strong-imgaug-body-shots-eval                       --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints/ --eval_dir=/checkpoints/evaluation --eval_name_suffix=-body-shots-eval --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1032-joint-puppet-close-up-wounds-strong-imgaug-cases-eval                            --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints/ --eval_dir=/checkpoints/evaluation --eval_name_suffix=-cases-eval      --eval_images --eval_heatmaps

mkdir -p /checkpoints/1033a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
cp /checkpoints/1032a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
mv /checkpoints/1033a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/1033a_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50_0001.h5

mkdir -p /checkpoints/1033b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
cp /checkpoints/1032b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
mv /checkpoints/1033b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/1033b_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50_0001.h5

mkdir -p /checkpoints/1033c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
cp /checkpoints/1032c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
mv /checkpoints/1033c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/1033c_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50_0001.h5

mkdir -p /checkpoints/1033d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
cp /checkpoints/1032d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50
mv /checkpoints/1033d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/*latest.h5 /checkpoints/1033d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50/1033d_Joint_Puppet_Closeup_Wounds_Strong_Imgaug_Fine_Tuning--RetinaNet-Resnet50_0001.h5

python main.py --purpose train    --env 1033-joint-puppet-close-up-wounds-strong-imgaug-fine-tuning                           --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation > train-1033-retina50.log 2>&1
python main.py --purpose evaluate --env 1033-joint-puppet-close-up-wounds-strong-imgaug-fine-tuning                           --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1033-joint-puppet-close-up-wounds-strong-imgaug-fine-tuning-body-shots-eval           --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation   --eval_name_suffix=-body-shots-eval                                   --eval_images --eval_heatmaps
python main.py --purpose evaluate --env 1033-joint-puppet-close-up-wounds-strong-imgaug-fine-tuning-cases-eval                --gpu_no 0 --net_type retina-resnet50 --data_dir=/home/samuelblattner/projects/ffhs-bachelor-thesis-wound-detection/data/vanilla_datasets --checkpoint_dir=/checkpoints --eval_dir=/checkpoints/evaluation                                     --eval_images --eval_heatmaps